### ISSUE TITLE
想咨询下作者，FFRouter 和 MGJRouter的有什么区别？或者说有什么特别的地方

### ISSUE THREAD

**Issue by yisRookie** [imlifengfeng/FFRouter#1]

**Comment by imlifengfeng** [comment]
你好，是这样的，如果只是使用基本的路由功能，目前主流的路由库都完全足够。但是，FFRouter 支持 URL Rewrite ，允许上线后不发版直接修改路由逻辑，可以实现类似网页的 302 跳转,也可以随时将打开 H5 页面逻辑改成打开 Native 页面，当然也可反之，具体使用场景可以根据实际情况来定。FFRouter 还支持 Route URL 时异步回调，比如可以从 A 页面跳转到 B 页面，B 页面异步回调数据给 A 页面。除此之外，还包含了一些小模块，比如 Log 打印、页面跳转工具方法等。
